#################
##
## This macro demonstrates the decay in LYSO process by using a 176Lu gun
##
#################

#Verbosity
/control/verbose 0
/tracking/verbose 0
/run/verbose 0
/process/verbose 0

#Initialisation of the run
/run/initialize

#Set mode variable to 2 to have the gun location in the LYSO (see DetectorConstruction)
/ABALONE_Event/generator/mode 2

#Set gun settings
/gun/particle ion
/gun/ion 71 176
/gun/energy 0. eV

#Create a particle
/run/beamOn 100